name: rtsp-samsung-tv Docker amd64 arm64 armv7 s390x

on:
  push:
    branches: master

jobs:
  multi:
    runs-on: ubuntu-latest
    environment: DOCKER
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_SECRET }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: |
            vassio/rtsp-samsung-tv:latest
            vassio/rtsp-samsung-tv:1.1.22
